# Generated by Django 3.2.7 on 2021-09-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('image_path', models.FilePathField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('geo_lat', models.FloatField()),
                ('geo_lon', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('resolve_date', models.DateField()),
                ('resolve_image', models.ImageField(upload_to='')),
                ('resolve_description', models.TextField()),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bkg.issuestatus')),
            ],
        ),
    ]
