# Generated by Django 3.2.7 on 2021-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
