# Generated by Django 3.2.7 on 2021-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkg', '0004_issue_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='geo_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolve_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolve_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
